name: handover
description: "Neighbors helping neighbors, skill by skill. A community-powered platform for exchanging skills and support."
publish_to: 'none'

version: 1.1.2+4

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.3.2
  http: ^1.2.0
  web_socket_channel: ^3.0.3

  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  geolocator: ^13.0.2

  cupertino_icons: ^1.0.8
  flutter_markdown: ^0.7.3

  image_picker:
  image_cropper: ^8.0.2

  qr_flutter: ^4.1.0

  onesignal_flutter: ^5.1.2
  purchases_flutter: ^10.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
